/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-09-15 08:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1663230861354L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1663230861353L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("	.wrapper{\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	.main-content{\r\n");
      out.write("		width: 1100px;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("	}\r\n");
      out.write("	.main-content__division {\r\n");
      out.write("		width: 400px;\r\n");
      out.write("		height: 400px;\r\n");
      out.write("		margin: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.main-content__division img {\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("<title>메인 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header 시작 -->\r\n");
      out.write("	");
      out.write("	\r\n");
      out.write("    \r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");
	String alertMsg = (String)session.getAttribute("alertMsg");
	String contextPath = (String)request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Header</title>\r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("	<!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- fontAwesome -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/567fbbaed5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	 function loginformPage(){\r\n");
      out.write("\r\n");
      out.write("	      	// 웹 어플리케이션의 디렉토리 구조가 url에 노출된다 => 보안에 취약\r\n");
      out.write("	      	// 단순한 정적인 페이지 요청이라고 하더라도 반드시 Servlet을 거쳐서 화면을 띄워주자\r\n");
      out.write("	      	// => url에 서블릿 맴핑값만 노출되게씀 하겠다.\r\n");
      out.write("	      	// localhost:8001/jsp/매핑\r\n");
      out.write("\r\n");
      out.write("	      	location.href = \"");
      out.print( contextPath );
      out.write("/loginform.me\";\r\n");
      out.write("	      	\r\n");
      out.write("	  }\r\n");
      out.write("	</script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header-wrapper\">\r\n");
      out.write("        <header id=\"header\" role=\"banner\">\r\n");
      out.write("            <div class=\"web-header\">\r\n");
      out.write("                <div class=\"special_bg\">\r\n");
      out.write("                    <div class=\"group_flex\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"logo_area\">\r\n");
      out.write("                            <div class=\"logo_default\">\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("\" class=\"logo__img\">\r\n");
      out.write("                                    <img src=\"");
      out.print( contextPath );
      out.write("/resources/img/icon.png\" alt=\"메인_로고\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <img class=\"logo__title--sm\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/title.png\" alt=\"닭치고_이거닭\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"main_title\">\r\n");
      out.write("                            <img src=\"");
      out.print( contextPath );
      out.write("/resources/img/title.png\" alt=\"닭치고_이거닭\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"search\" class=\"search_area\">\r\n");
      out.write("                            <div class=\"input-group mb-3\">\r\n");
      out.write("                                <input type=\"text\" autofocus class=\"form-control\" placeholder=\"검색어를 입력하세요\" name=\"sch\">\r\n");
      out.write("                                <div class=\"input-group-append\">\r\n");
      out.write("                                    <button onclick=\"searchProduct();\" class=\"btn btn-outline-secondary\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-lg fa-magnifying-glass\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 검색 기능 -->\r\n");
      out.write("                        <script>\r\n");
      out.write("                            function searchProduct(){\r\n");
      out.write("                                const keyword = $('.form-control').val();\r\n");
      out.write("                                \r\n");
      out.write("                                location.href = \"");
      out.print( contextPath );
      out.write("/search.pr?keyword=\" + keyword;\r\n");
      out.write("                            }\r\n");
      out.write("                        </script>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"service_area\">\r\n");
      out.write("                            ");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("                                <a href=\"javascript:loginformPage();\" >로그인</a>\r\n");
      out.write("                                <span>|</span>\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/loginenroll.me\">회원가입</a>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <a href=\"#\">장바구니</a>\r\n");
      out.write("                                <span>|</span>\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                                <span>|</span>\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath);
      out.write("/center.ce?cpage=1\">고객센터</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("                        <div class=\"user_greeting\">\r\n");
      out.write("                            <div class=\"user_greeting--user_name\">\r\n");
      out.write("                                <h3>");
      out.print( loginMember.getMemberName() );
      out.write("님</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"user_greeting--greeting\">\r\n");
      out.write("                                    <p>즐거운 쇼핑 되세요!</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- nav 시작 -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-sm sticky\"> <!-- bg-light 지움 -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <div type=\"button\" class=\"dropdown-toggle\">상품구매</div>\r\n");
      out.write("            <div class=\"dropdown-content\"> \r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/allproduct.pr\">전체상품</a>\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/newproduct.pr\">신상품</a>\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/rankingproduct.pr\">랭킹상품</a>\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/saleproduct.pr\">할인상품</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <div type=\"button\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.ev' \">이벤트</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <div type=\"button\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=1' \">자유게시판</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <div type=\"button\" onclick=\"location.href='");
      out.print(contextPath );
      out.write("/list.no?cpage=1' \">공지사항</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <div type=\"button\" class=\"dropdown-toggle\">마이페이지</div>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a class=\"forMember\" href=\"");
      out.print( contextPath );
      out.write("/cart.my\">장바구니</a>\r\n");
      out.write("                <a class=\"forMember\" href=\"");
      out.print( contextPath );
      out.write("/orderHistory.my\">주문내역</a>\r\n");
      out.write("                <a class=\"forMember\" href=\"");
      out.print( contextPath );
      out.write("/address.my\">배송지관리</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write(" 	<script>\r\n");
      out.write(" 		const msg = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write(" 		\r\n");
      out.write(" 		if(msg != \"null\"){\r\n");
      out.write(" 			alert(msg);\r\n");
      out.write(" 			\r\n");
      out.write(" 			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write(" 		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<!-- header 끝 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- main content 영역 -->\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		<div class=\"main-content\">\r\n");
      out.write("			<div class=\"main-content__division\">\r\n");
      out.write("				<img width=\"500px\" height=\"500px\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/product/KakaoTalk_20220708_091230921.png\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-content__division\">\r\n");
      out.write("				<img width=\"500px\" height=\"500px\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/product/KakaoTalk_20220708_091232050.png\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-content__division\">\r\n");
      out.write("				<img width=\"500px\" height=\"500px\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/product/KakaoTalk_20220708_091233245.png\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-content__division\">\r\n");
      out.write("				<img width=\"500px\" height=\"500px\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/product/KakaoTalk_20220708_091233245.png\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- main content 끝 -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- footer 시작 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("    .footer *{\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-wrapper{\r\n");
      out.write("        width: 1130px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: flex;\r\n");
      out.write("    }\r\n");
      out.write("    .footer{\r\n");
      out.write("        border-top: 1px solid #FFD000;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        resize: none;\r\n");
      out.write("    }\r\n");
      out.write("    .footer__row{\r\n");
      out.write("        background-color: #FAFBFC;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer__row--head{\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>푸터</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"footer-wrapper\">\r\n");
      out.write("            <div class=\"footer__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2 class=\"footer__row--head\">닭치고 이거닭</h2>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        바쁜일상 충분한단백질 또는 영양 섭취에 어려움을 <br>겪는 사람들을 위해\r\n");
      out.write("                        간편하고 빠른 건강 식품추천<br> 및 제공 업체를 소개 해주기위한 곳입니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"footer__row--head\">(주) 버터구이오징어</h4>\r\n");
      out.write("                    <span>대표 : 김정길</span><br>\r\n");
      out.write("                    <span>주소 : 중구 신당동</span><br>\r\n");
      out.write("                    <span>사업자등록번호 : 1234-56-1234</span><br>\r\n");
      out.write("                    <span>Copyright©닭치고이거닭 All rights reserved.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"footer__row--head\">고객센터</h3>\r\n");
      out.write("                    <h4>대표번호 : 02-123-4567</h4>\r\n");
      out.write("                    <p>월-금 10:00 ~ 17:00 (점심 12:30 ~ 13:30)<br>주말/공휴일 제외</p>\r\n");
      out.write("                    <p>Fax : 02-0000-0000</p>\r\n");
      out.write("                    <p>Email : chicken@asdasd.com</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<!-- footer 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
