/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-07-27 05:27:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Address;
import java.util.ArrayList;
import com.kh.member.model.vo.Member;

public final class addressList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/myPage/../common/header.jsp", Long.valueOf(1657251426536L));
    _jspx_dependants.put("/views/myPage/../common/footer.jsp", Long.valueOf(1655558372000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Address");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	ArrayList<Address> list = (ArrayList<Address>)request.getAttribute("list");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/addressList.css\">\n");
      out.write("	<title>마이페이지 - 배송지 등록/수정</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- header 시작 -->\n");
      out.write("	");
      out.write("	\n");
      out.write("    \n");

	Member loginMember = (Member)session.getAttribute("loginMember");
	String alertMsg = (String)session.getAttribute("alertMsg");
	String contextPath = (String)request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>Header</title>\n");
      out.write("    <!-- bootstrap -->\n");
      out.write("	<!-- Latest compiled and minified CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\n");
      out.write("    <!-- jQuery library -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js\"></script>\n");
      out.write("    <!-- Popper JS -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n");
      out.write("    <!-- Latest compiled JavaScript -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <!-- fontAwesome -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/567fbbaed5.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("	<script>\n");
      out.write("	 function loginformPage(){\n");
      out.write("\n");
      out.write("	      	// 웹 어플리케이션의 디렉토리 구조가 url에 노출된다 => 보안에 취약\n");
      out.write("	      	// 단순한 정적인 페이지 요청이라고 하더라도 반드시 Servlet을 거쳐서 화면을 띄워주자\n");
      out.write("	      	// => url에 서블릿 맴핑값만 노출되게씀 하겠다.\n");
      out.write("	      	// localhost:8001/jsp/매핑\n");
      out.write("\n");
      out.write("	      	location.href = \"");
      out.print( contextPath );
      out.write("/loginform.me\";\n");
      out.write("	      	\n");
      out.write("	  }\n");
      out.write("	</script>\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"header-wrapper\">\n");
      out.write("        <header id=\"header\" role=\"banner\">\n");
      out.write("            <div class=\"web-header\">\n");
      out.write("                <div class=\"special_bg\">\n");
      out.write("                    <div class=\"group_flex\">\n");
      out.write("\n");
      out.write("                        <div class=\"logo_area\">\n");
      out.write("                            <div class=\"logo_default\">\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("\" class=\"logo__img\">\n");
      out.write("                                    <img src=\"");
      out.print( contextPath );
      out.write("/resources/img/icon.png\" alt=\"메인_로고\">\n");
      out.write("                                </a>\n");
      out.write("                                <div>\n");
      out.write("                                    <img class=\"logo__title--sm\" src=\"");
      out.print( contextPath );
      out.write("/resources/img/title.png\" alt=\"닭치고_이거닭\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"main_title\">\n");
      out.write("                            <img src=\"");
      out.print( contextPath );
      out.write("/resources/img/title.png\" alt=\"닭치고_이거닭\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div id=\"search\" class=\"search_area\">\n");
      out.write("                            <div class=\"input-group mb-3\">\n");
      out.write("                                <input type=\"text\" autofocus class=\"form-control\" placeholder=\"검색어를 입력하세요\" name=\"sch\">\n");
      out.write("                                <div class=\"input-group-append\">\n");
      out.write("                                    <button onclick=\"searchProduct();\" class=\"btn btn-outline-secondary\" type=\"button\">\n");
      out.write("                                        <i class=\"fa-solid fa-lg fa-magnifying-glass\"></i>\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- 검색 기능 -->\n");
      out.write("                        <script>\n");
      out.write("                            function searchProduct(){\n");
      out.write("                                const keyword = $('.form-control').val();\n");
      out.write("                                \n");
      out.write("                                location.href = \"");
      out.print( contextPath );
      out.write("/search.pr?keyword=\" + keyword;\n");
      out.write("                            }\n");
      out.write("                        </script>\n");
      out.write("\n");
      out.write("                        <div class=\"service_area\">\n");
      out.write("                            ");
 if(loginMember == null) { 
      out.write("\n");
      out.write("                                <a href=\"javascript:loginformPage();\" >로그인</a>\n");
      out.write("                                <span>|</span>\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/loginenroll.me\">회원가입</a>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <a href=\"#\">장바구니</a>\n");
      out.write("                                <span>|</span>\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                                <span>|</span>\n");
      out.write("                                <a href=\"");
      out.print( contextPath);
      out.write("/center.ce?cpage=1\">고객센터</a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    ");
 if(loginMember != null){ 
      out.write("\n");
      out.write("                        <div class=\"user_greeting\">\n");
      out.write("                            <div class=\"user_greeting--user_name\">\n");
      out.write("                                <h3>");
      out.print( loginMember.getMemberName() );
      out.write("님</h3>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"user_greeting--greeting\">\n");
      out.write("                                    <p>즐거운 쇼핑 되세요!</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- nav 시작 -->\n");
      out.write("    <nav class=\"navbar navbar-expand-sm sticky\"> <!-- bg-light 지움 -->\n");
      out.write("\n");
      out.write("        <div class=\"dropdown\">\n");
      out.write("            <div type=\"button\" class=\"dropdown-toggle\">상품구매</div>\n");
      out.write("            <div class=\"dropdown-content\"> \n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/allproduct.pr\">전체상품</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/newproduct.pr\">신상품</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/rankingproduct.pr\">랭킹상품</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/saleproduct.pr\">할인상품</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"dropdown\">\n");
      out.write("            <div type=\"button\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.ev' \">이벤트</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"dropdown\">\n");
      out.write("            <div type=\"button\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?cpage=1' \">자유게시판</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"dropdown\">\n");
      out.write("            <div type=\"button\" onclick=\"location.href='");
      out.print(contextPath );
      out.write("/list.no?cpage=1' \">공지사항</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"dropdown\">\n");
      out.write("            <div type=\"button\" class=\"dropdown-toggle\">마이페이지</div>\n");
      out.write("            <div class=\"dropdown-content\">\n");
      out.write("                <a class=\"forMember\" href=\"");
      out.print( contextPath );
      out.write("/cart.my\">장바구니</a>\n");
      out.write("                <a class=\"forMember\" href=\"");
      out.print( contextPath );
      out.write("/orderHistory.my\">주문내역</a>\n");
      out.write("                <a class=\"forMember\" href=\"");
      out.print( contextPath );
      out.write("/address.my\">배송지관리</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write(" 	<script>\n");
      out.write(" 		const msg = \"");
      out.print( alertMsg );
      out.write("\";\n");
      out.write(" 		\n");
      out.write(" 		if(msg != \"null\"){\n");
      out.write(" 			alert(msg);\n");
      out.write(" 			\n");
      out.write(" 			");
 session.removeAttribute("alertMsg"); 
      out.write("\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		\n");
      out.write(" 	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write('	');
 int memberNo = loginMember.getMemberNo(); 
      out.write("\n");
      out.write("	<!-- header 끝 -->\n");
      out.write("\n");
      out.write("	<!-- content-영역 -->\n");
      out.write("	<div id=\"wrapper\">\n");
      out.write("\n");
      out.write("		<div class=\"content\">\n");
      out.write("\n");
      out.write("			<div class=\"content__header\">\n");
      out.write("				<div>\n");
      out.write("					<h2>배송지 관리</h2>\n");
      out.write("					<span style=\"color: rgba(0,0,0,0.5);\">* 배송지는 최대 5개까지 등록 가능합니다.</span>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<!-- 배송지리스트가 5개 이상이면 추가 버튼 비활설화 -->\n");
      out.write("				");
 if(list.size() < 5) { 
      out.write("\n");
      out.write("					<div>\n");
      out.write("						<button id=\"add-newAddress-btn\" type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#insertAddressForm\" data-backdrop=\"static\" data-keyboard=\"false\">+ 새로운 배송지 추가</button>\n");
      out.write("					</div>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<table class=\"list-area table table-striped\">\n");
      out.write("				\n");
      out.write("				<thead>\n");
      out.write("					<tr>\n");
      out.write("						<th>선택</th>\n");
      out.write("						<th>받으실 분</th>\n");
      out.write("						<th>배송 주소</th>\n");
      out.write("						<th>연락처</th>\n");
      out.write("						<th>관리</th>\n");
      out.write("					</tr>\n");
      out.write("				</thead>\n");
      out.write("\n");
      out.write("				<tbody>\n");
      out.write("					<!-- 배송지 등록을 안했으면 -->\n");
      out.write("					");
 if(list.isEmpty()) { 
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<td align=\"center\" colspan=\"6\">배송지를 등록해주세요</td>\n");
      out.write("						</tr>						\n");
      out.write("					");
 } else { 
      out.write("\n");
      out.write("						");
 for(Address a : list) { 
      out.write("\n");
      out.write("							<tr class=\"address-info\">\n");
      out.write("								<!-- \n");
      out.write("									addressNo = Address테이블의 PK\n");
      out.write("									curMain = 현재 행의 main 값(Y/N)\n");
      out.write("									receiver = 수취인\n");
      out.write("									location = 배송지명\n");
      out.write("									phone = 연락처\n");
      out.write("								-->\n");
      out.write("								<td class=\"hidden\"><input class=\"addressNo\" type=\"hidden\" name=\"addressNo\" value=\"");
      out.print( a.getAddressNo() );
      out.write("\"></td>\n");
      out.write("								<td><input type=\"radio\" name=\"curMain\" class=\"main\" value=\"");
      out.print( a.getMain() );
      out.write("\"></td>\n");
      out.write("								<td class=\"receiver\">");
      out.print( a.getReceiver() );
      out.write("</td>\n");
      out.write("								<td class=\"location\">");
      out.print( a.getLocation() );
      out.write("</td>\n");
      out.write("								<td class=\"phone\">");
      out.print( a.getPhone() );
      out.write("</td>\n");
      out.write("								<td>\n");
      out.write("									<div class=\"list-area__modify-btn\">\n");
      out.write("										<a class=\"btn-upd-add\" data-toggle=\"modal\" data-target=\"#modifyAddressForm\" data-backdrop=\"static\" data-keyboard=\"false\">수정</a>|\n");
      out.write("										<a class=\"btn-dlt-add\">삭제</a>\n");
      out.write("									</div>\n");
      out.write("								</td>\n");
      out.write("							</tr>\n");
      out.write("						");
 } 
      out.write("		\n");
      out.write("					");
 } 
      out.write(" \n");
      out.write("				</tbody>\n");
      out.write("			</table>\n");
      out.write("\n");
      out.write("			<!-- 신규 배송지 등록 모달 -->\n");
      out.write("			<div class=\"modal fade\" id=\"insertAddressForm\">\n");
      out.write("				<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("					<div class=\"modal-content\">\n");
      out.write("						<!-- Modal Header -->\n");
      out.write("						<div class=\"modal-header\">\n");
      out.write("							<h4 class=\"modal-title\">신규 등록</h4>\n");
      out.write("							<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<!-- Modal body -->\n");
      out.write("						<div class=\"modal-body\">\n");
      out.write("							<form id=\"new-address-form\" method=\"post\" action=\"insertAddress.my\">\n");
      out.write("								<!-- input hidden으로 현재 로그인된 사용자의 PK인 memberNo를 가져옴 -->\n");
      out.write("								<!-- 식별용으로 넘겨준다. -->\n");
      out.write("								<input type=\"hidden\" name=\"memberNo\" value=\"");
      out.print( memberNo );
      out.write("\">\n");
      out.write("								<table>\n");
      out.write("									<tr>\n");
      out.write("										<th>수취인 *</th>\n");
      out.write("										<td><input class=\"new-address-values\" type=\"text\" name=\"receiver\" required placeholder=\"받으시는 분 이름을 입력해 주세요\"></td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<th>주소 *</th>\n");
      out.write("										<td><input class=\"new-address-values\" type=\"text\" name=\"location\" required placeholder=\"주소를 입력해 주세요\"></td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<th>연락처 *</th>\n");
      out.write("										<td><input class=\"new-address-values\" type=\"text\" name=\"phone\" required placeholder=\"000-0000-0000 형식으로 입력해 주세요\"></td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<td colspan=\"2\">\n");
      out.write("											<!-- 첫 배송지 등록이면 무조건 기본배송지로 등록이 되어야함-->\n");
      out.write("											");
 if(list.isEmpty()) { 
      out.write("\n");
      out.write("												<div id=\"form-btn\">\n");
      out.write("													<!-- 여기에 input 히든을 넣은 이유는 disabled 가 설정되어있으면 value가 안넘어가짐 -->\n");
      out.write("													<!-- 컨트롤러에서 키값으로 setMain을 받아준다 -->\n");
      out.write("													<input type=\"hidden\" name=\"setMain\" value=\"Y\">\n");
      out.write("													<input id=\"setMainforNew\" type=\"checkbox\" disabled checked>\n");
      out.write("													<label for=\"setMainforNew\">처음 등록하시는 배송지는 자동으로 기본 배송지로 설정 됩니다.</label>\n");
      out.write("												</div>						\n");
      out.write("											");
 } else { 
      out.write("\n");
      out.write("												<div id=\"form-btn\">\n");
      out.write("													<input id=\"setMainforNew\" type=\"checkbox\" name=\"setMain\" value=\"Y\">\n");
      out.write("													<label for=\"setMainforNew\">기본 배송지로 설정</label>\n");
      out.write("												</div>\n");
      out.write("											");
 } 
      out.write("\n");
      out.write("										</td>\n");
      out.write("									</tr>\n");
      out.write("								</table>\n");
      out.write("								<!-- Modal footer -->\n");
      out.write("								<div class=\"modal-footer\">\n");
      out.write("									<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">취소</button>\n");
      out.write("									<button type=\"submit\" class=\"btn btn-default\" >등록</button>\n");
      out.write("								</div>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			");
 if(!list.isEmpty()) { 
      out.write("\n");
      out.write("				<button id=\"set-address-main\" type=\"button\" class=\"btn btn-default btn-lg\">기본 배송지로 설정</button>			\n");
      out.write("			");
 } 
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- 배송지 수정 모달 -->\n");
      out.write("	<div class=\"modal fade\" id=\"modifyAddressForm\">\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<!-- Modal Header -->\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					<h4 class=\"modal-title\">배송지 수정</h4>\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<!-- Modal body -->\n");
      out.write("				<form id=\"modify-form\" action=\"");
      out.print( contextPath );
      out.write("/modifyAddress.my\" method=\"post\">\n");
      out.write("					\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<!-- hidden inputs -->\n");
      out.write("						<input class=\"addressNo-upd\" type=\"hidden\" name=\"addressNo\">\n");
      out.write("						<input class=\"memberNo-upd\" type=\"hidden\" name=\"memberNo\" value=\"");
      out.print( memberNo );
      out.write("\">\n");
      out.write("						<input class=\"curMain-upd\" type=\"hidden\" name=\"curMain\">\n");
      out.write("\n");
      out.write("						<table>\n");
      out.write("							<tr>\n");
      out.write("								<th>수취인 *</th>\n");
      out.write("								<td><input class=\"receiver-upd\" type=\"text\" name=\"receiver\" required></td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<th>주소 *</th>\n");
      out.write("								<td><input class=\"location-upd\" type=\"text\" name=\"location\" required></td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<th>연락처 *</th>\n");
      out.write("								<td><input class=\"phone-upd\" type=\"text\" name=\"phone\" required></td>\n");
      out.write("							</tr>\n");
      out.write("							\n");
      out.write("							<tr>\n");
      out.write("								<td colspan=\"2\">\n");
      out.write("									<div class=\"form-btn\">\n");
      out.write("										<input id=\"newMain\" class=\"newMain\" type=\"checkbox\" value=\"Y\" name=\"newMain\" >\n");
      out.write("										<label for=\"newMain\">기본 배송지로 설정</label>\n");
      out.write("									</div>\n");
      out.write("								</td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("				<!-- Modal footer -->\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\" >수정완료</button>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- content-영역 --> \n");
      out.write("		\n");
      out.write("	<!-- footer 시작 -->\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<style>\n");
      out.write("    .footer *{\n");
      out.write("        margin: auto;\n");
      out.write("    }\n");
      out.write("    .footer-wrapper{\n");
      out.write("        width: 1130px;\n");
      out.write("        height: 100%;\n");
      out.write("        display: flex;\n");
      out.write("    }\n");
      out.write("    .footer{\n");
      out.write("        border-top: 1px solid #FFD000;\n");
      out.write("        display: flex;\n");
      out.write("        flex-direction: row;\n");
      out.write("        resize: none;\n");
      out.write("    }\n");
      out.write("    .footer__row{\n");
      out.write("        background-color: #FAFBFC;\n");
      out.write("        height: 100px;\n");
      out.write("        width: 100%;\n");
      out.write("        padding: 20px;\n");
      out.write("    }\n");
      out.write("    .footer__row--head{\n");
      out.write("        margin-bottom: 10px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<title>푸터</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"footer\">\n");
      out.write("        <div class=\"footer-wrapper\">\n");
      out.write("            <div class=\"footer__row\">\n");
      out.write("                <div>\n");
      out.write("                    <h2 class=\"footer__row--head\">닭치고 이거닭</h2>\n");
      out.write("                    <p>\n");
      out.write("                        바쁜일상 충분한단백질 또는 영양 섭취에 어려움을 <br>겪는 사람들을 위해\n");
      out.write("                        간편하고 빠른 건강 식품추천<br> 및 제공 업체를 소개 해주기위한 곳입니다.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer__row\">\n");
      out.write("                <div>\n");
      out.write("                    <h4 class=\"footer__row--head\">(주) 버터구이오징어</h4>\n");
      out.write("                    <span>대표 : 김정길</span><br>\n");
      out.write("                    <span>주소 : 중구 신당동</span><br>\n");
      out.write("                    <span>사업자등록번호 : 1234-56-1234</span><br>\n");
      out.write("                    <span>Copyright©닭치고이거닭 All rights reserved.</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer__row\">\n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"footer__row--head\">고객센터</h3>\n");
      out.write("                    <h4>대표번호 : 02-123-4567</h4>\n");
      out.write("                    <p>월-금 10:00 ~ 17:00 (점심 12:30 ~ 13:30)<br>주말/공휴일 제외</p>\n");
      out.write("                    <p>Fax : 02-0000-0000</p>\n");
      out.write("                    <p>Email : chicken@asdasd.com</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<!-- footer 끝 -->\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		$(function(){\n");
      out.write("\n");
      out.write("			// 새로운 배송지 추가 버튼 닫았다가 다시 실행했을때 text영역에 남아있던 값 초기화(공백)\n");
      out.write("			$(\"#add-newAddress-btn\").click(function(){\n");
      out.write("				$('.new-address-values').val(\"\");\n");
      out.write("			})\n");
      out.write("			\n");
      out.write("			// 화면이 로드될때 기본 배송지로 선택한 radio input의 checked \"true\";\n");
      out.write("			$(\".main\").each(function(index, item){\n");
      out.write("				if(this.value == \"Y\"){\n");
      out.write("					$(this).attr(\"checked\", true);\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("			\n");
      out.write("			// 배송지의 첫번째 행인 기본 배송지의 수정/삭제 버튼 선택하여 변수에 담아뒀음 \n");
      out.write("			const mainAddressDeletBtn = document.getElementsByClassName(\"btn-dlt-add\")[0];\n");
      out.write("\n");
      out.write("			// 삭제 버튼 => 기본 배송지의 삭제버튼은 비활성화\n");
      out.write("			$('.btn-dlt-add').click(function(){\n");
      out.write("				const ano = $(this).parents(\"tr\").children(\"td\").children(\".addressNo\").val();\n");
      out.write("\n");
      out.write("				if(this == mainAddressDeletBtn){ // 현재 클릭한 삭제버튼이 기본배송지의 삭제 버튼일 경우\n");
      out.write("					alert(\"기본 배송지는 삭제가 불가능허요~~\");\n");
      out.write("				} else{\n");
      out.write("					const answer = confirm(\"선택하신 배송지를 삭제하시겠습니까?\");\n");
      out.write("					if(answer){ // 컨펌창에서 확인을 누르면 삭제\n");
      out.write("						location.href = \"");
      out.print( contextPath );
      out.write("/deleteAddress.my?ano=\"+ano\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("\n");
      out.write("			// 수정하기 버튼 클릭시 해당 행의 Address정보가 폼에 기본값으로 입력됨\n");
      out.write("			// 제이쿼리 선택자를 통해 수정 버튼을 선택한후 this를 통해 해당 행의 정보(수취인, 배송지, 연락처)들의 값(text())을 변수에 담아둠\n");
      out.write("			// 각각의 값이 저장된 변수들을 btn 에 지정\n");
      out.write("			$('.btn-upd-add').click(function(){\n");
      out.write("				const curMain = $(this).parents(\".address-info\").children(\"td\").children(\".main\").val();\n");
      out.write("				const addressNo = $(this).parents(\".address-info\").children(\"td\").children(\".addressNo\").val();\n");
      out.write("				const receiver = $(this).parents(\".address-info\").children(\".receiver\").text();\n");
      out.write("				const location = $(this).parents(\".address-info\").children(\".location\").text();\n");
      out.write("				const phone = $(this).parents(\".address-info\").children(\".phone\").text();\n");
      out.write("\n");
      out.write("				switch(curMain){\n");
      out.write("					case \"Y\" : \n");
      out.write("								$(\".newMain\").attr(\"checked\", true).attr(\"disabled\", true);\n");
      out.write("								$(\".newMain\").val(\"Y\");\n");
      out.write("								break;\n");
      out.write("					case \"N\" : \n");
      out.write("								$(\".newMain\").attr(\"checked\", false).attr(\"disabled\", false);\n");
      out.write("								break;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				// 현재 설정된 값들을 각각의 인풋에 담아준다.\n");
      out.write("				// newMain의 input값은 \n");
      out.write("				$(\".curMain-upd\").val(curMain);\n");
      out.write("				$(\".addressNo-upd\").val(addressNo);\n");
      out.write("				$(\".receiver-upd\").val(receiver);\n");
      out.write("				$(\".location-upd\").val(location);\n");
      out.write("				$(\".phone-upd\").val(phone);\n");
      out.write("			})\n");
      out.write("			\n");
      out.write("			$('#set-address-main').click(function(){\n");
      out.write("\n");
      out.write("				// 현재 화면에서 체크된 배송지 가져오기\n");
      out.write("				// console.log($(\"input[type=radio]:checked\"));\n");
      out.write("				const beMain = $(\"input[type=radio]:checked\");\n");
      out.write("\n");
      out.write("				const ano = $(beMain).parent(\"td\").siblings(\".hidden\").children(\".addressNo\").val();\n");
      out.write("				const mno = \"");
      out.print( loginMember.getMemberNo() );
      out.write("\";\n");
      out.write("\n");
      out.write("				if(beMain.val() == \"Y\"){\n");
      out.write("					alert(\"이미 기본 배송지로 설정된 배송지입니다.\");\n");
      out.write("				} else{\n");
      out.write("					confirm(\"선택한 배송지를 기본배송지로 설정하시겠습니까?\");\n");
      out.write("					\n");
      out.write("					if(confirm) location.href = \"");
      out.print( contextPath );
      out.write("/setMainAddress.my?ano=\" + ano +\"&mno=\" + mno;\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("\n");
      out.write("		})\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
